### ISSUE TITLE
Why LDAP4J?

### ISSUE THREAD

**Issue by elecharny** [adaptiverecognition/ldap4j#1]
Hi,

just wondering why would we need this project, when Apache LDAP API is already proposing a non-blocking JAVA LDAP API for more than a decade with all the features you list, but supporting *all* the LDAP operations?

**Comment by directorydonkey** [comment]
See the [external issues file](https://github.com/adaptiverecognition/ldap4j/blob/master/EXTERNAL-ISSUES.md#apache-ldap-api). We've already taken a look at it.

**Comment by elecharny** [comment]
Regarding the ```LdapNetworkConnection.connect()```function, making it asynchronous would be a matter of hours to get it done.  But I wonder if it worths the pain: most of the time, one will use a connection pool, so the synchronous aspect of it it pretty irrelevant.

I'm not sure what the point about Integer padding? Could yo be more specific?

The Approx match implementation in Apache Directory Server is actually implemented as an Equal match for some reason: approx match is very language dependent, making it quite hard to implement. All in all, RFC states that it's up to server implementers to decide how to make it works.

You wrote "There's some integer parsing woes:", can you be a bit more specific?

Fast Bind is a AD extension, which can be implemented in both the LDAP API and the server. Actually, that would be easy in the API.

Regarding MINA, I'm not sure what's the issue with the IoSession.write function. The MINA API will just write what is required to be written, it's up to the caller to split has much data as needed (ie, you can call this function as many times you have bytes to be written). At the end of the day, the underlaying network will anyway only accept as much bytes as it can swallow, which means the write only store the data to be written in a buffer before sending what it can.

Same thing with IoSession.read(): there is no way to detect any EOF: it's protocol agnostic.It does not know how many bytes it will receive.

I have to check the other poionts you are making about MINA, you might have some valid points.

All in all, your inputs are very valuable. I wish we can collaborate in making this API a better one.

Thanks !

**Comment by directorydonkey** [comment]
While looking for an LDAP client library I had two strict requirements, all operations (we want to use) must be non-blocking, and must support timeouts. This was the minimum to start testing it.
The fact that `LdapNetworkConnection.connect()` blocks was just an instant no-go for us. Including it in a bunch of "non-blocking" methods just add to the injuries. I know it won't block when it's already connected.

The approx match note is just a reminder, that the approx match is not too well defined, and not too well tested either, and the apache ds documentation is confusing.
No-one wants to implement a "true" approx match, so I cannot write a unit test that shows that my approx and equality filters do different things on the server.

The so called integer parsing woe goes like this. The encoding of integers in DER is tag=2, length in bytes, bytes of the value, so 7 could be encoded as $02, $01, $07, and, not so clearly, 128 could be $02, $01, $80. But servers tend to interpret this last string as -128.
To make matters worse this is not even clear to people writing the servers, as this misinterpretation is not consistent.
And to make it even worse, some servers then pad this negative value to 4 bytes, so a message with id $80, sent using the 1-byte encondig, will result in a reply with message id $ffffff80.
Sending 128 as $02, $02, $00, $80 is much more palatable for servers.

The MINA note on complete writes is just a reminder what MINA can do, compared to java NIO, which is just POSIX sockets. We have no need of partial writes at all for an LDAP client.

Please, don't fret over the external issues file too much, it's more of a remainder for us, why we did what we did, and what the known issues are so we don't have to repeat all our bumblings over and over again. It's not really a bug list.
While I'm not happy what I had to do to make MINA work with ldap4j, it works just fine now.

**Comment by elecharny** [comment]
Interesting. To quote your last sentence, "Please, don't fret over the external issues file too much, it's more of a remainder for us", that is a very valid reason for doing what you are doing.
My point is more like we should try to collaborate, and make the LDAP API better (whether you keep going on with your effort or not is not relevant), as I do think we can improve the current implementation.

Typically, the blocking connection could be removed, but there is slightly more work to do than I thought: the fact that we wait for the connection to be completed is easy (we already use a Future for that), the main  issue is the SSL part, which also need to be asynchronous.

I would set aside the approx match as you said is not really an API issue, but rather a server side implementation thing.

Regarding the Integer parsing (beside the fact that LDAP is using BER not DER, but this is not relevant for Integers), I'm pretty sure the Apache Directory server properly deal with IDs (ie 02 01 80 is decoded as -128, not 128. The 128 integer should be encoded as 02 02 00 80). ASN.1 basic encoding rule for integers says that:
* positive integers are encoded as 0bbb-bbbb bbbb-bbbb...bbbb-vvvv if the high order bit is 0, or 0000-0000 1bbb-bbbb bbbb-bbbb... if the high order bit is 1
* negative integres are encoded as an absolute value, which gets 1's complemented first, then 2's encoded. So -128 is encoded as 128 (1000-000) then  0111-111 then 1000-000, ir 0x80. 
So 128 is encoded 02 02 00 80 and -128 is encoded 02 01 80.

**Comment by elecharny** [comment]
I've added a connectAsync() method in Apache LDAP API, but this is only part of the solution. What is missing:
* addition of a closeListener (a method that will be called when the connection is closed, because we *must* send a set of Notice of Disconnect for every pending operations)
* add a Binary Attribute detection (this is used to know how to deal with attribute's value, some of them being tagged as binary)
* set the initial message ID counter to 0
* Create a connectionCloseFuture
* eventually establish the TLS layer
* keep a track of the network layer.

In a non blocking connection, all of that has to be handled by the caller, which is a pain. For instance, you not only have to check that the connection has been created, but also that it has been secured, and a LDAP connection may have been secured in two ways:
* plain TLS handshake
* or startTLS extended operation

This is why I have doubts about the necessity of a non-blocking connection.

**Comment by directorydonkey** [comment]
I've looked around following your pointers, and decided that you're right. Negative integers can be described, but are not used by LDAP. And I've fixed several bugs relating to this. Thank you.
I rewrote the section about this in the external issues, and apache ds seems to work correctly in this regard after all!

I'm not sure what I can bring to the apache ldap api table. Tls is hard.
Ldap4j can do fully non-blocking connect, starttls, and connect+tls now, but tls renegotiation and dropping the tls layer are not supported yet. Both will be a major undertaking, and they will likely brake the current abstraction.
Our tls code is implemented as a wrapper over a nonblocking-posix-socket-like interface. Would it be cheaper to port it than just rewrite it? I'm not sure... Would it even fit?

**Comment by elecharny** [comment]
The main issue with the current Apache LDAP API async API is that you still have to *wait* for the result to arrive. That means polling, or blocking wait. Which is absurd. I'd like it to be based on something like an event loop, so that the user can process the response as it arrives.
The current implementation require some change, like :
* either being able to pass a callback to the async function
* or have a Listener associated with each operation
* or use a dedicated thread for that purpose.

At this point, it would be just a layer on top of the existing API, where the Future we use would be replaced by something more like Events.

This is where I think we need to go. 

Regarding TLS, there are two aspects:
* either you get it set while creating the connection
* or you establish it once the connection has been set
It's not really that different, the only complicated part is to be sure the underlying network API support a TLS negociation on the fly - that means being able to handle the HS when required, and deal with all the consequences regarding any potential ongoing operations in a multi-threaded env -.

In any case, HS is *costly* (like  a few tens of ms), and being able to handle it asynchronously is a big plus.

In any case, you should let the underlying layer deal with that (ie, MINA or NETTY or whatever).

**Comment by directorydonkey** [comment]
I'm gonna close this now. Thanks for the integer tips.
